### PR TITLE
added support for ruff linting and autoformatting

### PR DESCRIPTION
**Pull request by telamonian**

### CODE REVIEW

**Comment by huchenlei** [comment]
Are we nuking the current setup of linting with pylint and autoformatting with black?

**Comment by telamonian** [comment]
> Are we nuking the current setup of linting with pylint and autoformatting with black?

@huchenlei That's the idea. ruff alone can handle both linting and formatting (it has tools for both). It should also support more features/rules and be much more flexible than black

**Comment by telamonian** [comment]
@SocketSecurity ignore pypi/ruff@0.6.1

**Comment by telamonian** [comment]
No need to worry about the failure of the ruff_check GA, that gets fixed when the initial ruff lint/format is applied in #157

**Pull request merged**
